import {SelectedToolProvider} from "../components/context/SelectedTool.tsx"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{<SelectedToolProvider>{children}</SelectedToolProvider>}</body>
    </html>
  )
}
