import { SelectedToolProvider } from "../components/context/SelectedTool";
import { SelectedColorProvider } from "../components/context/Color";
import { DrawSettingsProvider } from "@/components/context/drawSettings";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DrawSettingsProvider>
          <SelectedToolProvider>
          <SelectedColorProvider>
            {children}
          </SelectedColorProvider>
          </SelectedToolProvider>
        </DrawSettingsProvider>
      </body>
    </html>
  );
}
